spring:
  data:
    redis:
      port: 6379
      host: 10.181.30.10
      password: 532129
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com.example: debug
my:
  secretKey: q12w34e56r78
  upload: 'E:/' #文件上传保存地址