spring:
  datasource:
    password: 532129
    url: jdbc:mysql://localhost:3306/project?createDataBaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    com.example: debug
my:
  secretKey: q12w34e56r78
  upload: 'E:/ProjectFile/' #文件上传保存地址