spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/mybatis?
    createDataBaseIfNotExist=true
    &serverTimezone=Asia/Shanghai'
    username: root
    password: 532129
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true

logging:
  level:
    sql: debug #控制台输出sql拼接语句
    root: warn #控制台输出
    com:
      example: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
my:
  secretKey: 2Q1WER5BAQ79PLO0Q

